### ISSUE TITLE
Clean up model

### ISSUE THREAD

**Issue by hawkrobe** [judithfan/visual_communication_in_context#5]
* Reparameterize to alpha * inf - beta * cost
* Do Savage-Dickey for model comparison 
* Marginalize over posterior params instead of taking MAP 
  * Do this in webppl (for human and direct fc6)
* Look at posterior predictives for individual sketches 
* Look at prior predictives (what is odds here?)

**Comment by judithfan** [comment]
consolidated into consolidated paper todos issue
